Alter pre-commit hook better handle several errors
Instead of only reporting a single erroneous file per commit attempt,
report all of them at once.

diff --git a/misc/pre-commit b/misc/pre-commit
--- a/misc/pre-commit
+++ b/misc/pre-commit
@@ -14,6 +14,8 @@ ASTYLE_PARAMETERS="--style=kr -p -H -U -W3 -k3 -c -s"
 FILE_PATTERN="\.(c|cpp|h)$"
 IGNORE_PATTERN="^doc/"
 
+error=0
+
 for file in `git diff-index --cached --name-only HEAD --diff-filter=ACMR| egrep $FILE_PATTERN| egrep -v $IGNORE_PATTERN` ; do
     # nf is the temporary checkout. This makes sure we check against the
     # revision in the index (and not the checked out version).
@@ -26,14 +28,17 @@ for file in `git diff-index --cached --name-only HEAD --diff-filter=ACMR| egrep 
     rm "${nf}"
     if [ $r != 0 ] ; then
         echo "================================================================================================="
-        echo " Code style error in: $file "
-        echo " "
-        echo " Please fix before committing. Don't forget to run git add before trying to commit again. "
-        echo " If the whole file is to be committed, this should work (run from the top-level directory): "
-        echo " "
-        echo " astyle ${ASTYLE_PARAMETERS} -n $file; git add $file; git commit"
-        echo " "
+        echo " astyle ${ASTYLE_PARAMETERS} -n $file"
         echo "================================================================================================="
-        exit 1
+        error=1
     fi
 done
+
+if [ ${error} -ne 0 ]; then
+    echo "================================================================================================="
+    echo " Code style errors in one or more files"
+    echo " "
+    echo " Please fix before committing. Don't forget to run git add before trying to commit again. "
+    echo "================================================================================================="
+    exit 1
+fi
